version: "3.8"

services:
  app:
    build: .
    restart: always
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - nginx_network
      - database_network

  database:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=robot
      - POSTGRES_PASSWORD=robot
      - POSTGRES_DB=robot
    networks:
      - database_network

  nginx:
    image: nginx
    ports:
      - "80:80"
    networks:
      - nginx_network
    depends_on:
      - app

networks:
  nginx_network:
    name: nginx_network
    driver: bridge
  database_network:
    name: database_network
    driver: bridge

volumes:
  postgres_data:
