FROM python:3.11
WORKDIR /data
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip install kombu --force-reinstall --no-cache-dir
COPY .. .
EXPOSE 8000
CMD celery -A robot_dreams worker
